language: node_js

services:
  - docker

script:
  - ./node-env prod npm run lint
  - ./node-env prod npm run test
  - if [ $TRAVIS_BRANCH = 'master' ] ; then ./node-env prod npm run build:android; fi

