version: '3'
services:
  node:
    build: .
    network_mode: host
    working_dir: /usr/app/app
    environment:
      - EXPO_USER
      - EXPO_PASSWORD
      - EXPO_APPLE_ID
      - EXPO_APPLE_PASSWORD
